### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by airon90**
Fixed translations

### CODE REVIEW

**Comment by Rafostar** [comment]
I am not sure about "Cast Settings" translation. I would like to match other names from drop down menu (like Wired Settings, VPN Settings, Account Settings etc.) instead of calling it simply "Settings". Isn't there more suitable word for "Cast" in Italian?

Also could you update translation file before translating?
```
make potfile
make mergepo
```
There is one more new word recently added to master, so it would be nice to have it already translated while someone is interested in translating. After that add only `it.po` file commit to this PR. Thanks.

**Comment by Rafostar** [comment]
"Cast Media" is translated as "Condividi media". Why "Cast Settings" cannot be translated as "Condividi impostazioni"? Is there anything wrong with "Fallito caricamento del media"? I am not speaking Italian so I am simply asking.

**Comment by airon90** [comment]
1. You cast media ("Condividi media") but you don't cast settings ("condividi impostazioni"). You are setting the cast, which litteraly is translated as "Impostazioni condivisione" but is too long and not standard. Just "Impostazioni" ("settings") is okay.
2. Italian language is a "SVO" language, so I moved the subject before the past participle of the verb. It's not an error but it is a better translation

**Comment by Rafostar** [comment]
I would prefer properly generated `it.po` file using software like `Poedit`, but will merge this anyway. Thanks.

**Comment by airon90** [comment]
> I would prefer properly generated it.po file using software like Poedit, but will merge this anyway. Thanks.

Sorry but I never used Poedit ^^' I will start using it ;)

**Pull request merged**
